// <auto-generated />
using System;
using FightBuilder.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FightBuilder.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20191130055728_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FightBuilder.Models.Equipment", b =>
                {
                    b.Property<int>("EquipmentID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color");

                    b.Property<string>("Description");

                    b.Property<int>("FireDam");

                    b.Property<int>("FireDef");

                    b.Property<int>("MagDam");

                    b.Property<int>("MagDef");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("PhysDam");

                    b.Property<int>("PhysDef");

                    b.Property<string>("Type");

                    b.HasKey("EquipmentID");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("FightBuilder.Models.Fighter", b =>
                {
                    b.Property<int>("FighterID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ChestEquipmentID");

                    b.Property<string>("Color");

                    b.Property<string>("Description");

                    b.Property<int?>("GlovesEquipmentID");

                    b.Property<int?>("HeadEquipmentID");

                    b.Property<int?>("LeftHandEquipmentID");

                    b.Property<int>("Losses");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int?>("PantsEquipmentID");

                    b.Property<int?>("RightHandEquipmentID");

                    b.Property<int?>("RingEquipmentID");

                    b.Property<int?>("ShoesEquipmentID");

                    b.Property<int>("Wins");

                    b.HasKey("FighterID");

                    b.HasIndex("ChestEquipmentID");

                    b.HasIndex("GlovesEquipmentID");

                    b.HasIndex("HeadEquipmentID");

                    b.HasIndex("LeftHandEquipmentID");

                    b.HasIndex("PantsEquipmentID");

                    b.HasIndex("RightHandEquipmentID");

                    b.HasIndex("RingEquipmentID");

                    b.HasIndex("ShoesEquipmentID");

                    b.ToTable("Fighters");
                });

            modelBuilder.Entity("FightBuilder.Models.Fighter", b =>
                {
                    b.HasOne("FightBuilder.Models.Equipment", "Chest")
                        .WithMany()
                        .HasForeignKey("ChestEquipmentID");

                    b.HasOne("FightBuilder.Models.Equipment", "Gloves")
                        .WithMany()
                        .HasForeignKey("GlovesEquipmentID");

                    b.HasOne("FightBuilder.Models.Equipment", "Head")
                        .WithMany()
                        .HasForeignKey("HeadEquipmentID");

                    b.HasOne("FightBuilder.Models.Equipment", "LeftHand")
                        .WithMany()
                        .HasForeignKey("LeftHandEquipmentID");

                    b.HasOne("FightBuilder.Models.Equipment", "Pants")
                        .WithMany()
                        .HasForeignKey("PantsEquipmentID");

                    b.HasOne("FightBuilder.Models.Equipment", "RightHand")
                        .WithMany()
                        .HasForeignKey("RightHandEquipmentID");

                    b.HasOne("FightBuilder.Models.Equipment", "Ring")
                        .WithMany()
                        .HasForeignKey("RingEquipmentID");

                    b.HasOne("FightBuilder.Models.Equipment", "Shoes")
                        .WithMany()
                        .HasForeignKey("ShoesEquipmentID");
                });
#pragma warning restore 612, 618
        }
    }
}
